# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nostradamus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="nostradamus.proto",
    package="nostradamus",
    syntax="proto3",
    serialized_options=b"\242\002\003NOS",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x11nostradamus.proto\x12\x0bnostradamus"0\n\x11TopicLabelRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t"\x86\x01\n\x0fTopicLabelReply\x12@\n\nprediction\x18\x01 \x03(\x0b\x32,.nostradamus.TopicLabelReply.PredictionEntry\x1a\x31\n\x0fPredictionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32Y\n\x0cTopicLabeler\x12I\n\x07Predict\x12\x1e.nostradamus.TopicLabelRequest\x1a\x1c.nostradamus.TopicLabelReply"\x00\x42\x06\xa2\x02\x03NOSb\x06proto3',
)


_TOPICLABELREQUEST = _descriptor.Descriptor(
    name="TopicLabelRequest",
    full_name="nostradamus.TopicLabelRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="title",
            full_name="nostradamus.TopicLabelRequest.title",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="body",
            full_name="nostradamus.TopicLabelRequest.body",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=34,
    serialized_end=82,
)


_TOPICLABELREPLY_PREDICTIONENTRY = _descriptor.Descriptor(
    name="PredictionEntry",
    full_name="nostradamus.TopicLabelReply.PredictionEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="nostradamus.TopicLabelReply.PredictionEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="nostradamus.TopicLabelReply.PredictionEntry.value",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=170,
    serialized_end=219,
)

_TOPICLABELREPLY = _descriptor.Descriptor(
    name="TopicLabelReply",
    full_name="nostradamus.TopicLabelReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="prediction",
            full_name="nostradamus.TopicLabelReply.prediction",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _TOPICLABELREPLY_PREDICTIONENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=85,
    serialized_end=219,
)

_TOPICLABELREPLY_PREDICTIONENTRY.containing_type = _TOPICLABELREPLY
_TOPICLABELREPLY.fields_by_name["prediction"].message_type = _TOPICLABELREPLY_PREDICTIONENTRY
DESCRIPTOR.message_types_by_name["TopicLabelRequest"] = _TOPICLABELREQUEST
DESCRIPTOR.message_types_by_name["TopicLabelReply"] = _TOPICLABELREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicLabelRequest = _reflection.GeneratedProtocolMessageType(
    "TopicLabelRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _TOPICLABELREQUEST,
        "__module__": "nostradamus_pb2"
        # @@protoc_insertion_point(class_scope:nostradamus.TopicLabelRequest)
    },
)
_sym_db.RegisterMessage(TopicLabelRequest)

TopicLabelReply = _reflection.GeneratedProtocolMessageType(
    "TopicLabelReply",
    (_message.Message,),
    {
        "PredictionEntry": _reflection.GeneratedProtocolMessageType(
            "PredictionEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _TOPICLABELREPLY_PREDICTIONENTRY,
                "__module__": "nostradamus_pb2"
                # @@protoc_insertion_point(class_scope:nostradamus.TopicLabelReply.PredictionEntry)
            },
        ),
        "DESCRIPTOR": _TOPICLABELREPLY,
        "__module__": "nostradamus_pb2"
        # @@protoc_insertion_point(class_scope:nostradamus.TopicLabelReply)
    },
)
_sym_db.RegisterMessage(TopicLabelReply)
_sym_db.RegisterMessage(TopicLabelReply.PredictionEntry)


DESCRIPTOR._options = None
_TOPICLABELREPLY_PREDICTIONENTRY._options = None

_TOPICLABELER = _descriptor.ServiceDescriptor(
    name="TopicLabeler",
    full_name="nostradamus.TopicLabeler",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=221,
    serialized_end=310,
    methods=[
        _descriptor.MethodDescriptor(
            name="Predict",
            full_name="nostradamus.TopicLabeler.Predict",
            index=0,
            containing_service=None,
            input_type=_TOPICLABELREQUEST,
            output_type=_TOPICLABELREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_TOPICLABELER)

DESCRIPTOR.services_by_name["TopicLabeler"] = _TOPICLABELER

# @@protoc_insertion_point(module_scope)
